MyProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Medical_Management import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls',namespace='cart')),
    path('orders/', include('orders.urls',namespace='orders')),
    path('',views.index),
    path('master', views.master),
    path('registration', views.registration),
    path('login1', views.login1, name="login1"),
    path('header', views.header),
    path('about', views.about),
    path('contact', views.contact),
    path('contact_data', views.contact_data),
    path('services', views.services),
    path('product',views.product),
    path('product_detail/<int:id>', views.product_detail, name="product_detail"),
    path('supplier_registration', views.supplier_registration),
    path('supplierinsert', views.supplierinsert),
    path('user_registration', views.user_registration),
    path('userinsert', views.userinsert),
    path('tablets', views.tablets),
    path('inhaler', views.inhaler),
    path('injection', views.injection),
    path('capsules', views.capsules),
    path('drops', views.drops),
    path('logout1', views.logout1, name="logout1"),
    path('logout2', views.logout2, name="logout2"),

    path('index1',views.index1),
    path('about1', views.about1),
    path('contact1', views.contact1),
    path('services1', views.services1),
    path('product1',views.product1),
    path('Cust_master', views.Cust_master),

    #admin side url
    path('admin/dashboard', views.dashboard,name="dashboard"),
    path('admin/admin_master', views.admin_master,name="admin_master"),
    path('admin/signin', views.signin,name="signin"),
    path('admin/add_category', views.add_category,name="add_category"),
    path('admin/category_list',views.category_list,name="category_list"),
    path('admin/edit_category/<int:id>', views.edit_category, name="edit_category"),
    path('admin/update_category/<int:id>', views.update_category, name="edit_category"),
    path('admin/delete_category/<int:id>', views.delete_category, name="delete_category"),
    path('admin/category_data',views.category_data,name="category_data"),
    path('admin/add_supplier', views.add_supplier,name="add_supplier"),
    path('admin/edit_supplier/<int:id>', views.edit_supplier, name="edit_supplier"),
    path('admin/update_supplier/<int:id>', views.update_supplier, name="update_supplier"),
    path('admin/delete_supplier/<int:id>', views.delete_supplier, name="delete_supplier"),
    path('admin/supplier_data',views.supplier_data,name="supplier_data"),
    path('admin/supplier_list',views.supplier_list,name="supplier_list"),
    path('admin/add_medicine', views.add_medicine,name="add_medicine"),
    path('admin/medicine_list',views.medicine_list,name="medicine_list"),
    path('admin/edit_medicine/<int:id>', views.edit_medicine, name="edit_medicine"),
    path('admin/update_medicine/<int:id>', views.update_medicine, name="update_medicine"),
    path('admin/delete_medicine/<int:id>', views.delete_medicine, name="delete_medicine"),
    path('admin/add_customer',views.add_customer,name="add_customer"),
    path('admin/edit_cust/<int:id>', views.edit_cust, name="edit_cust"),
    path('admin/update_cust/<int:id>', views.update_cust, name="update_cust"),
    path('admin/delete_cust/<int:id>', views.delete_cust, name="delete_cust"),
    path('admin/cust_data',views.cust_data,name="cust_data"),
    path('admin/customer_list',views.customer_list,name="customer_list"),
    path('admin/feedback', views.feedback,name="feedback"),
    path('admin/delete_feedback/<int:id>', views.delete_feedback, name="delete_feedback"),
    path('admin/admin_logout', views.admin_logout,name="admin_logout"),

    #supplier side url
    path('Supplier/supplier_master', views.supplier_master),
    path('Supplier/supplier_dashboard', views.supplier_dashboard),
    path('Supplier/supplier_add_customer',views.supplier_add_customer,name="supplier_add_customer"),
    path('Supplier/supplier_edit_cust/<int:id>', views.supplier_edit_cust, name="supplier_edit_cust"),
    path('Supplier/supplier_update_cust/<int:id>', views.supplier_update_cust, name="supplier_update_cust"),
    path('Supplier/supplier_delete_cust/<int:id>', views.supplier_delete_cust, name="supplier_delete_cust"),
    path('Supplier/supplier_cust_data',views.supplier_cust_data,name="supplier_cust_data"),
    path('Supplier/supplier_customer_list',views.supplier_customer_list,name="supplier_customer_list"),
    path('Supplier/supplier_add_medicine',views.supplier_add_medicine,name="supplier_add_medicine"),
    path('Supplier/supplier_medicine_list',views.supplier_medicine_list,name="supplier_medicine_list"),
    path('Supplier/supplier_medical_data', views.supplier_medical_data, name="supplier_medical_data"),
    path('Supplier/manage_order',views.manage_order,name="manage_order"),
    path('Supplier/supplier_view_order/<int:id>', views.supplier_view_order, name="supplier_view_order"),
    path('Supplier/supplier_feedback', views.supplier_feedback, name="supplier_feedback"),
    path('Supplier/supplier_delete_feedback/<int:id>', views.supplier_delete_feedback, name="supplier_delete_feedback"),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_detail',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from Medical_Management.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    if request.session.has_key('user_email'):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
                     quantity=cd['quantity'],
                     update_quantity=cd['update'])
        return redirect('cart:cart_detail')
    else:
        #return render(request, "User/login.html")
        return redirect('login1')


def cart_remove(request, product_id):
    if request.session.has_key('user_email'):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('cart:cart_detail')
    else:
        return render(request, "User/login.html")

def cart_detail(request):
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        cart = Cart(request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                       'update': True})
        return render(request, "cart/detail.html",{"user_email":email,"cart": cart})
    else:
        return render(request, "User/login.html")

cart/templates/cart/detail.html
{% extends 'User/Cust_master.html' %}

{% block title %}Your Shopping Cart{% endblock %}

<!-- css -->
	{% load static %}
  <link href="{% static 'User/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'User/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{% static 'User/plugins/cubeportfolio/css/cubeportfolio.min.css' %}">
  <link href="{% static 'User/css/nivo-lightbox.css' %}" rel="stylesheet" />
  <link href="{% static 'User/css/nivo-lightbox-theme/default/default.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'User/css/owl.carousel.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'User/css/owl.theme.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'User/css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'User/css/style.css' %}" rel="stylesheet">

{% block body %}
<!-- Navbar End -->
    <div class="product" style="border:1px solid orange; padding-top:120px;">
	    <div class="sub_product">
            <div class="prod_header">
                <center><h1>Your shopping cart</h1></center>
            </div>
            <center>
            <table border="1" id="carttable" cellspacing="10" cellpadding="10">
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit Price</th>
                    <th>Price</th>
                </tr>
                {% for item in cart %}
                    {% with product=item.product %}
                <tr align="center">
                    <td align="center" width="30%">
                         <a href="{{ product.get_absolute_url }}">
                             <img src="{% if product.prod_photo %}{{ product.prod_photo.url }}{% endif %}" width="80%" height="15%">
                         </a>
                    </td>
                    <td>{{ product.prod_name }}</td>
                    <td>
                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {% csrf_token %}
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" id="update" value="Update">
                        </form>
                    </td>
                    <td>
                        <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                    </td>
                    <td class="num">₱{{ item.price }}</td>
                    <td class="num">₱{{ item.total_price }}</td>
                </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total" align="center">
                    <th>Total</th>
                    <th colspan="4"></th>
                    <th class="num">₱{{ cart.get_total_price }}</th>
                </tr>
            </table>
                </center>
            <br>
            <p class="textbtn">
                <a href="../product1" style="border:1px solid red;margin-left:80px;padding:10px; color:white;" class="btn btn-warning">Continue shopping</a>
                <a href="{% url 'orders:order_create' %}" class="btn btn-warning" style="border:1px solid red;margin-left:950px;padding:10px;color:white;">Checkout</a>
            </p>
        </div>
    </div>
{% endblock %}