MyProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Medical_Management import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls',namespace='cart')),
    path('orders/', include('orders.urls',namespace='orders')),
    path('',views.index),
    path('master', views.master),
    path('registration', views.registration),
    path('login1', views.login1, name="login1"),
    path('header', views.header),
    path('about', views.about),
    path('contact', views.contact),
    path('contact_data', views.contact_data),
    path('services', views.services),
    path('product',views.product),
    path('product_detail/<int:id>', views.product_detail, name="product_detail"),
    path('supplier_registration', views.supplier_registration),
    path('supplierinsert', views.supplierinsert),
    path('user_registration', views.user_registration),
    path('userinsert', views.userinsert),
    path('tablets', views.tablets),
    path('inhaler', views.inhaler),
    path('injection', views.injection),
    path('capsules', views.capsules),
    path('drops', views.drops),
    path('logout1', views.logout1, name="logout1"),
    path('logout2', views.logout2, name="logout2"),

    path('index1',views.index1),
    path('about1', views.about1),
    path('contact1', views.contact1),
    path('services1', views.services1),
    path('product1',views.product1),
    path('Cust_master', views.Cust_master),

    #admin side url
    path('admin/dashboard', views.dashboard,name="dashboard"),
    path('admin/admin_master', views.admin_master,name="admin_master"),
    path('admin/signin', views.signin,name="signin"),
    path('admin/add_category', views.add_category,name="add_category"),
    path('admin/category_list',views.category_list,name="category_list"),
    path('admin/edit_category/<int:id>', views.edit_category, name="edit_category"),
    path('admin/update_category/<int:id>', views.update_category, name="edit_category"),
    path('admin/delete_category/<int:id>', views.delete_category, name="delete_category"),
    path('admin/category_data',views.category_data,name="category_data"),
    path('admin/add_supplier', views.add_supplier,name="add_supplier"),
    path('admin/edit_supplier/<int:id>', views.edit_supplier, name="edit_supplier"),
    path('admin/update_supplier/<int:id>', views.update_supplier, name="update_supplier"),
    path('admin/delete_supplier/<int:id>', views.delete_supplier, name="delete_supplier"),
    path('admin/supplier_data',views.supplier_data,name="supplier_data"),
    path('admin/supplier_list',views.supplier_list,name="supplier_list"),
    path('admin/add_medicine', views.add_medicine,name="add_medicine"),
    path('admin/medicine_list',views.medicine_list,name="medicine_list"),
    path('admin/edit_medicine/<int:id>', views.edit_medicine, name="edit_medicine"),
    path('admin/update_medicine/<int:id>', views.update_medicine, name="update_medicine"),
    path('admin/delete_medicine/<int:id>', views.delete_medicine, name="delete_medicine"),
    path('admin/add_customer',views.add_customer,name="add_customer"),
    path('admin/edit_cust/<int:id>', views.edit_cust, name="edit_cust"),
    path('admin/update_cust/<int:id>', views.update_cust, name="update_cust"),
    path('admin/delete_cust/<int:id>', views.delete_cust, name="delete_cust"),
    path('admin/cust_data',views.cust_data,name="cust_data"),
    path('admin/customer_list',views.customer_list,name="customer_list"),
    path('admin/feedback', views.feedback,name="feedback"),
    path('admin/delete_feedback/<int:id>', views.delete_feedback, name="delete_feedback"),
    path('admin/admin_logout', views.admin_logout,name="admin_logout"),

    #supplier side url
    path('Supplier/supplier_master', views.supplier_master),
    path('Supplier/supplier_dashboard', views.supplier_dashboard),
    path('Supplier/supplier_add_customer',views.supplier_add_customer,name="supplier_add_customer"),
    path('Supplier/supplier_edit_cust/<int:id>', views.supplier_edit_cust, name="supplier_edit_cust"),
    path('Supplier/supplier_update_cust/<int:id>', views.supplier_update_cust, name="supplier_update_cust"),
    path('Supplier/supplier_delete_cust/<int:id>', views.supplier_delete_cust, name="supplier_delete_cust"),
    path('Supplier/supplier_cust_data',views.supplier_cust_data,name="supplier_cust_data"),
    path('Supplier/supplier_customer_list',views.supplier_customer_list,name="supplier_customer_list"),
    path('Supplier/supplier_add_medicine',views.supplier_add_medicine,name="supplier_add_medicine"),
    path('Supplier/supplier_medicine_list',views.supplier_medicine_list,name="supplier_medicine_list"),
    path('Supplier/supplier_medical_data', views.supplier_medical_data, name="supplier_medical_data"),
    path('Supplier/manage_order',views.manage_order,name="manage_order"),
    path('Supplier/supplier_view_order/<int:id>', views.supplier_view_order, name="supplier_view_order"),
    path('Supplier/supplier_feedback', views.supplier_feedback, name="supplier_feedback"),
    path('Supplier/supplier_delete_feedback/<int:id>', views.supplier_delete_feedback, name="supplier_delete_feedback"),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_detail',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

Medical_Management/models.py
from django.db import models

class Admin(models.Model):
    Username=models.CharField(max_length=20)
    Password=models.CharField(max_length=50)
    class Meta:
        db_table='Admin'
    def __str__(self):
        return self.Username
class Category(models.Model):
    category_title=models.CharField(max_length=20)
    class Meta:
        db_table='Category'
    def __str__(self):
        return self.category_title

class Product(models.Model):
    prod_name=models.CharField(max_length=20)
    category_id=models.ForeignKey(Category,on_delete=models.CASCADE)
    prod_photo=models.ImageField(upload_to='images/product/')
    prod_price=models.IntegerField()
    prod_description=models.TextField()
    class Meta:
        db_table='Product'
    def __str__(self):
        return self.prod_name
class Customer(models.Model):
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    gender = models.CharField(max_length=6)
    bod = models.DateField()
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=20)
    mobile = models.BigIntegerField()
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='images/User/')
    class Meta:
        db_table='Customer'
    def __str__(self):
        return self.firstname

class Supplier(models.Model):
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    shopname = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=20)
    mobile = models.BigIntegerField()
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='images/Supplier/')
    class Meta:
        db_table='Supplier'
    def __str__(self):
        return self.firstname

class ContactUs(models.Model):
    name=models.CharField(max_length=20)
    email=models.EmailField(max_length=30)
    mobile=models.BigIntegerField()
    message=models.TextField()
    class Meta:
        db_table='ContactUs'
    def __str__(self):
        return self.name

Medical_Management/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth import authenticate,login,logout
from cart.forms import CartAddProductForm
from .models import Category,Product,Customer,Supplier,ContactUs
from orders.models import Order,OrderItem

# ----------------------------User Side--------------------------------

def index(request):
    return render(request,"User/index.html")

def master(request):
    return render(request,"User/master.html")

def registration(request):
    return render(request,"User/registration.html")

def login1(request):
    if request.session.has_key('supplier_email'):
        email = request.session['supplier_email']
        return render(request, "Supplier/supplier_dashboard.html", {'supplier_email': email})
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        return render(request, "User/index1.html", {'user_email': email})
    context = {}
    if request.method == 'POST':
        U = request.POST['checkuser']
        if U == "Supplier":
            email = request.POST['email']
            password = request.POST['password']
            try:
                user = Supplier.objects.get(email=email,password= password)
            except:
                context['Error'] = "Invalid username and password"
                return render(request, "User/login.html", context)
            if user is not None:
                request.session['supplier_email'] = user.email
                return HttpResponseRedirect('Supplier/supplier_dashboard')
            else:
                context['Error'] = "Invalid username and password"
                return render(request, "User/login.html", context)
        elif U == "Customer":
            email = request.POST['email']
            password = request.POST['password']
            try:
                user = Customer.objects.get(email = email,password=password)
            except:
                context['Error'] = "Invalid username and password"
                return render(request, "User/login.html", context)
            if user is not None:
                request.session['user_email'] = user.email
                return HttpResponseRedirect('index1')
            else:
                context['Error'] = "Invalid username and password"
                return render(request, "User/login.html", context)
    else:
        return render(request, "User/login.html")

def logout1(request):
    try:
        del request.session['supplier_email']
    except:
        pass
    messages.success(request, 'You have successfully logged out..!')
    return redirect("/login1")

def logout2(request):
    try:
        del request.session['user_email']
    except:
        pass
    messages.success(request, 'You have successfully logged out..!')
    return redirect("/login1")

def header(request):
    return render(request,"User/header.html")

def about(request):
    return render(request,"User/Aboutus.html")

def contact(request):
    return render(request,"User/Contactus.html")

def contact_data(request):
    context = {}
    if request.method == "POST":
        form = ContactUs(name=request.POST['name'],email=request.POST['email'],mobile=request.POST['mobile'],message=request.POST['message'])
        try:
            form.save()
            messages.success(request, 'Successfully Inserted Record..!')
            if request.session.has_key('user_email'):
                return redirect("contact")
            else:
                return redirect("contact")
        except:
            context['Error'] = "Not Insert Record Please Try Again..!"
            return render(request, "User/Contactus.html",context)
    else:
        return render(request, "User/Contactus.html")

def services(request):
    return render(request,"User/services.html")

def product(request):
    datas=Product.objects.all()
    return render(request,"User/product.html",{'datas':datas})

def product_detail(request,id):
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        product = Product.objects.get(id=id)
        cart_product_form = CartAddProductForm()
        return render(request, "User/details1.html",
                      {"user_email": email, 'product': product, 'cart_product_form': cart_product_form})
    else:
        product = Product.objects.get(id=id)
        cart_product_form = CartAddProductForm()
        return render(request,"User/details.html",{'product':product,'cart_product_form':cart_product_form})


def user_registration(request):
    return render(request,"User/user_registration.html")

def userinsert(request):
    context = {}
    if request.method=="POST":
        form = Customer(firstname=request.POST['firstname'], lastname=request.POST['lastname'],
                        gender=request.POST['gender'], bod=request.POST['bod'], address=request.POST['address'],
                        city=request.POST['city'], email=request.POST['email'], password=request.POST['password'],
                        mobile=request.POST['mobile'], photo=request.FILES['img'])
        try:
            form.save()
            messages.success(request, 'Successfully Insert Record..!')
            return redirect("user_registration")
        except:
            context['Error'] = "Not Insert Record Please Try Again..!"
            return render(request, "User/user_registration.html", context)


def supplier_registration(request):
    return render(request,"User/supplier_registration.html")

def supplierinsert(request):
    context = {}
    if request.method=="POST":
        form = Supplier(firstname=request.POST['firstname'], lastname=request.POST['lastname'],
                        shopname=request.POST['shopname'], address=request.POST['address'],
                        city=request.POST['city'], email=request.POST['email'], password=request.POST['password'],
                        mobile=request.POST['mobile'], photo=request.FILES['img'])
        try:
            form.save()
            messages.success(request, 'Successfully Insert Record..!')
            return redirect("supplier_registration")
        except:
            context['Error'] = "Not Insert Record Please Try Again..!"
            return render(request, "User/supplier_registration.html", context)

def tablets(request):
    return render(request,"User/tablets.html")

def inhaler(request):
    return render(request,"User/inhaler.html")

def injection(request):
    return render(request,"User/injection.html")

def capsules(request):
    return render(request,"User/capsules.html")

def drops(request):
    return render(request,"User/drops.html")

@login_required(login_url="login1")
def Cust_master(request):
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        return render(request, "User/Cust_master.html",{"user_email":email})
    else:
        return render(request, "User/login.html")

def index1(request):
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        return render(request, "User/index1.html",{"user_email":email})
    else:
        return render(request, "User/login.html")

def product1(request):
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        datas = Product.objects.all()
        return render(request, "User/product1.html",{"user_email":email,'datas': datas})
    else:
        return render(request, "User/login.html")

def contact1(request):
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        return render(request, "User/contact1.html",{"user_email":email})
    else:
        return render(request, "User/login.html")

def about1(request):
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        return render(request, "User/about1.html",{"user_email":email})
    else:
        return render(request, "User/login.html")

def services1(request):
    if request.session.has_key('user_email'):
        email = request.session['user_email']
        return render(request, "User/services1.html",{"user_email":email})
    else:
        return render(request, "User/login.html")
# ----------------------------Admin Side--------------------------------

def signin(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        print(user)
        if user is not None and user.is_active:
            auth.login(request, user)
            request.session['admin_id'] = user.id
            return HttpResponseRedirect('dashboard')
        else:
            context['Error'] = "Invalid username and password"
            return render(request, "Admin/admin_login.html", context)
    else:
        return render(request, "Admin/admin_login.html")

@login_required(login_url="signin")
def admin_master(request):
    return render(request,"Admin/admin_master.html")

@login_required(login_url="signin")
def dashboard(request):
    return render(request,"Admin/dashboard.html")

@login_required(login_url="signin")
def add_category(request):
    return render(request,"Admin/add_category.html")

@login_required(login_url="signin")
def category_data(request):
    context = {}
    if request.method == "POST":
        form = Category(category_title=request.POST['title'])
        try:
            form.save()
            messages.success(request, 'Successfully Inserted Record..!')
            return redirect("add_category")
        except:
            context['Error'] = "Not Insert Record Please Try Again..!"

Medical_Management/templates/User/Aboutus.html
{% extends 'User/master.html' %}

{% block title %}About Us{% endblock %}

<!-- css -->
	{% load static %}
  <link href="{% static 'User/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'User/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{% static 'User/plugins/cubeportfolio/css/cubeportfolio.min.css' %}">
  <link href="{% static 'User/css/nivo-lightbox.css' %}" rel="stylesheet" />
  <link href="{% static 'User/css/nivo-lightbox-theme/default/default.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'User/css/owl.carousel.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'User/css/owl.theme.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'User/css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'User/css/style.css' %}" rel="stylesheet">

{% block body %}
  <!-- Section: intro -->
    <section id="intro" class="intro">
      <div class="intro-content">
        <div class="container">
          <div class="row">
            <div class="con_about">
                <center>
                    <div class="sub_about">
                        <div id="about_header">

                        </div>
                        <div class="about">
                            <div class="about1">
                                <img src="{% static 'User/img/dummy/one.jpg' %}" class="img-responsive" alt="" />
                            </div>
                            <br>
                            <div class="about1">
                                <h2>About  Medical Shop</h2>
                                <p>
Student Medical Shop is small family owned business that has been selling medical supplies. We are an authorized distributor of many recognized brands including Welch Allyn and 3M Littmann Stethoscopes. The mission of studentmedicalshop.com is to offer medical professionals and allied health students diagnostic equipment in a range of prices affordable to any budget. We provide the highest quality and most trusted brands in diagnostic equipment at competitive prices with reliable and dedicated personal service. By doing so, we enable our customers to obtain the equipment necessary to be successful healthcare professionals or students. We are happy to help with any questions you have.</p>
                            </div>
                            <div id="clear"></div>
                        </div>
                    </div>
                </center>
            </div>

          </div>
        </div>
      </div>
    </section>

    <!-- /Section: intro -->
{% endblock %}

Medical_Management/templates/User/Contactus.html
{% extends 'User/master.html' %}

{% block title %}Contact Us{% endblock %}

<!-- css -->
	{% load static %}
  <link href="{% static 'User/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'User/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{% static 'User/plugins/cubeportfolio/css/cubeportfolio.min.css' %}">
  <link href="{% static 'User/css/nivo-lightbox.css' %}" rel="stylesheet" />
  <link href="{% static 'User/css/nivo-lightbox-theme/default/default.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'User/css/owl.carousel.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'User/css/owl.theme.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'User/css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'User/css/style.css' %}" rel="stylesheet">

{% block body %}
  <!-- Section: intro -->
    <section id="intro" class="intro">
      <div class="intro-content">
        <div class="container">
          <div class="row">
            <center>
        <div id="formcon">
            <div class="headcon">
                <h3>Contact Us </h3>
            </div>

            <div class="form1">
                <form action="contact_data" method="post">
                    {% csrf_token %}
                    <table  class="login" style="width:30%;solid gray;">
                        <tr>
                            <th colspan="2" align="center">
                                {% if Error%}
                                    <b style="color: red; border: 1px solid gray;">
                                        {{ Error }}
                                    </b>
                                {% elif messages %}
                                    {% for message in messages %}
                                        <b style="color: green; border: 1px solid gray;">
                                            {{ message }}
                                        </b>{% endfor %}
                                {% endif %}
                            </th>
                        </tr>
                        <tr>
                            <th style="color:black;">Name</th>
                            <td style="padding:10px;"><input type="text" name="name" placeholder="Name" id="input" title="Name" style="color:black;border:1px solid black;background: transparent;" required></td>
                        </tr>
                        <tr>
                            <th style="color:black;">Email</th>
                            <td style="padding:10px;"><input type="email" name="email" placeholder="Email" id="input" title="Email" style="color:black;border:1px solid black;background: transparent;" required></td>
                        </tr>
                        <tr>
                            <th style="color:black;">Mobile</th>
                            <td style="padding:10px;"><input type="number" name="mobile" placeholder="Mobile" id="input" title="Mobile" style="color:black;border:1px solid black;background: transparent;" required></td>
                        </tr>
                        <tr>
                        	<th style="color:black;">Message</th>
                            <td style="padding:10px;"><textarea type="text" name="message" placeholder="Message" id="textarea" title="Message" style="color:black;border:1px solid black;background: transparent;" required></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" align="center" style="padding:10px;">
                                <input type="submit" value="Send" id="btn" style="background-color:blue;color:white; width:100px; height:40px;">
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
            <div id="clear"></div>
        </div>
    </center>

          </div>
        </div>
      </div>
    </section>

    <!-- /Section: intro -->
{% endblock %}

Medical_Management/templates/User/details.html
{% extends 'User/master.html' %}

{% block title %}product{% endblock %}

<!-- css -->
	{% load static %}
  <link href="{% static 'User/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'User/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{% static 'User/plugins/cubeportfolio/css/cubeportfolio.min.css' %}">
  <link href="{% static 'User/css/nivo-lightbox.css' %}" rel="stylesheet" />
  <link href="{% static 'User/css/nivo-lightbox-theme/default/default.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'User/css/owl.carousel.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'User/css/owl.theme.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'User/css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'User/css/style.css' %}" rel="stylesheet">

{% block body %}
<div class="product">
	<div class="sub_product">
		<div class="prod_header">
			<h1>Details Of Product</h1>
		</div>
        <center>
            <div style="width:50%;padding-top:30px;" >
              <img src="{{ product.prod_photo.url }}" style="width:100%;height:100%;">
                <table cellpadding="10" cellspacing="10">
                    <tr>
                        <th align="left"><font size="5">Name  </font></th>
                        <td style="padding-left:20px;"><font size="5">{{ product.prod_name }}</font></td>
                    </tr>
                    <tr>
                        <th align="left"><font size="5">Category  </font></th>
                        <td style="padding-left:20px;"><font size="5">{{ product.category_id }}</font></td>
                    </tr>
                    <tr>
                        <th align="left"><font size="5">Price  </font></th>
                        <td style="padding-left:20px;"><font size="5">₱{{ product.prod_price }}</font></td>
                    </tr>
                     <tr>
                        <th align="left"><font size="5">Description  </font></th>
                        <td style="padding-left:20px;"><font size="5">{{ product.prod_description }}</font></td>
                    </tr>
                </table>
                <form method="post" action="{% url "cart:cart_add" product.id %}">
                {% csrf_token %}
                 {{ cart_product_form }}
                  <p><input type="submit" class="btn btn-warning" value="Add to Cart" style="border: none;outline: 0;padding: 12px;color: white;text-align: center;cursor: pointer;width: 100%;font-size: 18px;"></p>
                 </form>
                <h3><a href="../product" style="color:black;text-decoration:none;" class="btn btn-success">Back</a></h3>
            </div>
        </center>
	</div>
</div>
{% endblock %}

Medical_Management/templates/User/header.html
{% load static %}
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation" style="background-color: orange;" >
      
      <div class="container navigation">

        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
          <a class="navbar-brand" href="index.html">

                </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">



            <ul class="nav navbar-nav text-white">

                <li>
                    <a href="/">Home</a>
                </li>

                <li><a href="/user_registration">User</a></li>
                <li><a href="/supplier_registration">Supplier</a></li>
                <li><a href="login1">Login</a></li>
              <li><a href="product">Products</a>
              </li>
            <li><a href="contact">Contact Us</a></li>
            <li><a href="about">About Us</a></li>
              <li><a href="services">Services</a></li>
                <li>
                    <a  class="addcart" title="Add Cart" style="color:black;">Cart(<span id="cart">0</span>)</a>
                </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

Medical_Management/templates/User/header1.html
{% load static %}
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation" style="background-color: orange">

      <div class="container navigation">

        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
          <a class="navbar-brand" href="index.html">

                </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">



            <ul class="nav navbar-nav">

                <li>
                    <a href="index1">Home</a>
                </li>
                <li><a href="product1">Products</a></li>
                <li><a href="contact1">Contact Us</a></li>
                <li><a href="about1">About Us</a></li>
                <li><a href="services1">Services</a></li>
                <li><a href="index1">{{ user_email }}</a></li>
                <li><a href="/logout2">Logout</a></li>
                <li>
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url 'cart:cart_detail' %}" style="color:black; text-decoration:none;">Cart(<span id="cart">{{ total_items }}</span>)</a>
                        {% else %}
                            <a href="{% url 'cart:cart_detail' %}" style="color:black; text-decoration:none;">Cart(<span id="cart">{{ total_items }}</span>)</a>
                        {% endif %}
                    {% endwith %}
                </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>